# Generated by Django 3.2.8 on 2022-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0002_auto_20220320_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyacademiccalendar',
            name='week_create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
