# Generated by Django 4.0.2 on 2022-04-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0005_academicday'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicday',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
