# Generated by Django 4.0.2 on 2022-04-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0006_academicday_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicday',
            name='school_day',
            field=models.CharField(choices=[('NR', 'Normal'), ('RE', 'Recesso'), ('VA', 'Férias'), ('HO', 'Feriado')], default='NR', max_length=2),
        ),
    ]
