# Generated by Django 4.0.2 on 2022-04-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0007_academicday_school_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicday',
            name='holiday',
        ),
        migrations.AlterField(
            model_name='academicday',
            name='course',
            field=models.CharField(choices=[('GR', 'Graduação'), ('PG', 'Pós Graduação'), ('MI', 'Master in Information Technology'), ('MB', 'MBAS')], default='GR', max_length=2),
        ),
    ]
