# Generated by Django 4.0.2 on 2022-04-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0008_remove_academicday_holiday_alter_academicday_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicday',
            name='year',
        ),
    ]
