# Generated by Django 4.0.2 on 2022-04-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0009_remove_academicday_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyacademiccalendar',
            name='week_start',
        ),
    ]
